version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend   # Путь к папке с Dockerfile бэка
    container_name: backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend   # Путь к папке с фронтом
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080  # или backend:8080 внутри сети Docker
    command: ["npm", "start"]

volumes:
  postgres_data:
